version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:21-jdk

    working_directory: /.

    steps:
      - checkout
      - run:
            name: Log in to Docker Hub
            command: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

      - run:
          name: Set up JDK 21
          command: |
            java -version

      - restore_cache:
          key: maven-v1-{{ checksum "pom.xml" }}

      - run:
          name: Build with Maven
          command: mvn clean install -B

      - save_cache:
          paths:
            - ~/.m2
          key: maven-v1-{{ checksum "pom.xml" }}

  test:
    docker:
      - image: circleci/openjdk:21-jdk

    working_directory: /.

    steps:
      - checkout

      - restore_cache:
          key: maven-v1-{{ checksum "pom.xml" }}

      - run:
          name: Run tests with Maven
          command: mvn test

workflows:
  version: 2
  build:
    jobs:
      - build
      - test:
          requires:
            - build

