# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  test:
    docker:
      - image: circleci/openjdk:21-jdk
    steps:
      - checkout
      # Replace this with a real test runner invocation
      - restore_cache:
          key: maven-v1-{{ checksum "pom.xml" }}

      - run:
          name: Run tests with Maven
          command: mvn test
  build:
    docker:
      - image: circleci/openjdk:21-jdk
    steps:
      - checkout
      - run:
          name: Set up JDK 21
          command: |
            sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk-21/bin/java 1
            sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/jdk-21/bin/javac 1
            java -version
            javac -version
      # Replace this with steps to build a package, or executable
      - run:
          name: Build and test with Maven
          command: mvn clean install
      - restore_cache:
          key: maven-v1-{{ checksum "pom.xml" }}
      - store_artifacts:
          path: example.txt
      - save_cache:
          paths:
            - ~/.m2
          key: maven-v1-{{ checksum "pom.xml" }}
  deploy:
    docker:
      - image: circleci/openjdk:21-jdk
    steps:
      # Replace this with steps to deploy to users
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'
workflows:
  example:
    jobs:
      - build
      - test:
          requires:
            - build


            
