# This is a basic workflow to help you get started with Actions
name: Java Spring Boot CI/CD

on:
  push:
    branches:
      - develop  # Set the branch to trigger the pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and Test
        run: mvn clean install --file pom.xml

      - name: Security Scan
        run: |
          # Run a security scan for sensitive data.
          # You can add security scan steps here.

      - name: Deploy to Test Environment
        if: success()
        run: |
          # Add deployment steps to deploy to your test environment.

